name = "odometer"
version = "1.0.0"

description = "Cycle through item combinations."
licences = ["Apache-2.0"]
repository = { type = "github", user = "JosephTLyons", repo = "odometer" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glearray = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
